# Practicing with the Numpy unique() function

In [11]:
import numpy as np

In [12]:
gar = np.array(['b','b','a','a','a','c','c','c'])   #original list

In [13]:
np.unique(gar)

array(['a', 'b', 'c'], dtype='<U1')

In [14]:
unique_elements = np.unique(gar)
print(unique_elements) #list with unique elements sorted

['a' 'b' 'c']


In [15]:
np.unique(gar, return_index=True)

(array(['a', 'b', 'c'], dtype='<U1'), array([2, 0, 5], dtype=int64))

In [16]:
unique_elements, first_positions = np.unique(gar, return_index=True)
print(unique_elements) #list with unique elements
print(first_positions) #list with first position (index) on original list of each unique element

['a' 'b' 'c']
[2 0 5]


In [17]:
np.unique(gar, return_index=True, return_inverse=True)

(array(['a', 'b', 'c'], dtype='<U1'),
 array([2, 0, 5], dtype=int64),
 array([1, 1, 0, 0, 0, 2, 2, 2], dtype=int64))

In [18]:
unique_elements, first_positions, index_elements = np.unique(gar, return_index=True, return_inverse=True)
print(unique_elements) #list with unique elements
print(first_positions) #list with first position (index) on original list of each unique element
print(index_elements) #list with corresponding index on the unique_element list of each element on original list

['a' 'b' 'c']
[2 0 5]
[1 1 0 0 0 2 2 2]


In [19]:
np.unique(gar, return_index=True, return_inverse=True, return_counts=True)

(array(['a', 'b', 'c'], dtype='<U1'),
 array([2, 0, 5], dtype=int64),
 array([1, 1, 0, 0, 0, 2, 2, 2], dtype=int64),
 array([3, 2, 3], dtype=int64))

In [20]:
unique_elements, first_positions, index_elements, nb_elements = np.unique(gar, return_index=True, return_inverse=True, return_counts=True)
print(unique_elements) #list with unique elements
print(first_positions) #list with first position (index) on original list of each unique element
print(index_elements) #list with corresponding index on the unique_element list of each element on original list
print(nb_elements) #list with the number of unique elements

['a' 'b' 'c']
[2 0 5]
[1 1 0 0 0 2 2 2]
[3 2 3]


In [21]:
np.sort(first_positions)

array([0, 2, 5], dtype=int64)

In [22]:
np.argsort(first_positions)

array([1, 0, 2], dtype=int64)

In [23]:
unique_elements[np.argsort(first_positions)]

array(['b', 'a', 'c'], dtype='<U1')

In [24]:
np.sort(index_elements)

array([0, 0, 0, 1, 1, 2, 2, 2], dtype=int64)

In [25]:
np.argsort(index_elements)

array([2, 3, 4, 0, 1, 5, 6, 7], dtype=int64)

In [26]:
gar[np.argsort(index_elements)]

array(['a', 'a', 'a', 'b', 'b', 'c', 'c', 'c'], dtype='<U1')

In [27]:
np.sort(gar)

array(['a', 'a', 'a', 'b', 'b', 'c', 'c', 'c'], dtype='<U1')